### PR TITLE
Add upstreams and targets

### LINKED ISSUE #69: Support new upstream api
https://github.com/Mashape/kong/pull/1735

### PR DESCRIPTION
**Pull request by dgarlitt**
This adds upstream and target capabilities to kongconfig as requested
in: mybuilder/kongfig#69

This change closes #69

### CODE REVIEW

**Comment by CyExy** [comment]
Great stuff, thanks for the PR. I'll pull it down and review properly before merging.

**Comment by dgarlitt** [comment]
@CyExy I noticed that the checks were failing and looked at the TravisCi build. It seems that Kong is not running on localhost. Any idea why that may be?

**Comment by CyExy** [comment]
I'll look into the Tarvis issue.

**Comment by CyExy** [comment]
Please could you rebase on the master, that fixes travis build

**Comment by dgarlitt** [comment]
@CyExy Let me know if there are any changes to be made.

**Comment by CyExy** [comment]
Sorry for the delay, and thanks for rebasing. I'm going to look through it first thing tomorrow morning.

**Comment by CyExy** [comment]
@dgarlitt I would like to send you a kongfig t-shirt, if interested please email me your postal address, size etc to sten [at] mybuilder.com add your github username as well so I know its you :)

58737 2f402996 2fnnuownvr8rvnefw 2fkongfig-mockup

**Pull request merged**
