### PR TITLE
feat(Acl): add ACL supports

### PR DESCRIPTION
**Pull request by Freyskeyd**
#### What's this PR purpose?

Adding ACL credentials supports

Signed-off-by: Simon Paitrault <contact@freyskeyd.fr>

### CODE REVIEW

**Comment by Freyskeyd** [comment]
We need to be able to define `array` on credentials objects.
We can define multiple keys

**Comment by CyExy** [comment]
@Freyskeyd This PR look good, but I don't understand the `array` issue.

**Comment by Freyskeyd** [comment]
I'm unable to define multiple keys for now.

Array support on credentials could allow this.

**Comment by JnMik** [comment]
Check my PR, I can handle multiple ACL group.
https://github.com/mybuilder/kongfig/pull/24

**Comment by JnMik** [comment]
@CyExy  This PR should be decline if https://github.com/mybuilder/kongfig/pull/24 has been accepted.

**Comment by CyExy** [comment]
@Freyskeyd Thanks for you pull, hope #24 fits your needs, feedback welcome.

**Pull request closed without merging**
