### PR TITLE
add protocol cli option

### PR DESCRIPTION
**Pull request by pklingem**
allows passing `--protocol https` when running `kongfig` for endpoints that are SSL enabled.  `protocol` defaults to `http`.

### CODE REVIEW

**Comment by pklingem** [comment]
@CyExy any chance of merging this?

**Comment by CyExy** [comment]
Sorry forgot all about it – holidays. I think rather than `--protocol https` just `--https` would work better.

**Comment by pklingem** [comment]
@CyExy I can get on board with that, lemme tweak...

**Comment by CyExy** [comment]
Thanks! I published a new batch, kongfig@1.2.3

**Comment by pklingem** [comment]
@CyExy thanks!

**Pull request merged**
