### PR TITLE
Add support for ACLs

### PR DESCRIPTION
**Pull request by JnMik**

### CODE REVIEW

**Comment by JnMik** [comment]
Sorry I wasn't aware that Freyskeyd had already started some dev on ACL, 
but well, I needed it to work asap so here's my PR.

**Comment by JnMik** [comment]
I have completely separate the credentials from the ACL, 

as Mashape do in their documentation 

http://screencast.com/t/WG29AAnIfBQ3

Maybe I've done too much compared to Freyskeyd .. 

Comments are welcome!

**Comment by CyExy** [comment]
Looks great, thanks! I'll check it out and release a new version tomorrow.

**Comment by pklingem** [comment]
:+1: excited for this.

**Pull request merged**
