### PR TITLE
Referencing consumers by username

### PR DESCRIPTION
**Pull request by CyExy**
Some API plugins like rate-limiting allow adding consumer specific rules.

- [x] Add support for accepting username and translate it to consumer_id
- [x] Change config dump to translate consumer_id to username

### CODE REVIEW

**Comment by tophercullen** [comment]
#82 should support most of this

**Comment by CyExy** [comment]
@tophercullen while rebasing on top of the master, I rebased out dumping the customer id in the config. https://github.com/mybuilder/kongfig/pull/82/files#diff-e1e4bea3884d253e9824510e186398dfR24

It would be great to get some of your configs that you used to test this feature.

**Comment by tophercullen** [comment]
Something along these lines
```
consumers:
  - username: user1
    custom_id: 9c6088ba-41f0-44be-9879-a784d8683787
  - username: user2
    custom_id: 1c6088ba-41f0-44be-9879-a784d8683788
  - username: user3
    custom_id: 3c6088ba-41f0-44be-9879-a784d8683789


apis:
  - name: myapi 
    ensure: "present" 
    attributes:
      upstream_url: https://service-api/ # (required)
      hosts: []
      uris: /
      methods: []
      strip_uri: false
      preserve_host: true
      retries: 5
      upstream_connect_timeout: 60000
      upstream_read_timeout: 60000
      upstream_send_timeout: 60000
      https_only: true # (required)
      http_if_terminated: false
    plugins:
      - name: rate-limiting 
        ensure: "present" 
        username: user1
        attributes: 
          consumer_id: baduserid
          config:
            minute: 4 
      - name: rate-limiting 
        ensure: "present" 
        attributes: 
          config:
            minute: 2
      - name: rate-limiting 
        ensure: "present" 
        custom_id: 1c6088ba-41f0-44be-9879-a784d8683788
        attributes: # the plugin attributes
          consumer_id: baduserid
          config:
            minute: 3


plugins:
  - name: rate-limiting
    ensure: "present"
    attributes:
      config:
        minute: 1
  - name: rate-limiting
    ensure: "present"
    custom_id: 3c6088ba-41f0-44be-9879-a784d8683789
    attributes:
      consumer_id: badid
      config:
        minute: 5
  - name: rate-limiting
    ensure: "present"
    username: user3
    attributes:
      consumer_id: badid
      config:
        minute: 6
```

**Comment by thehighlander** [comment]
I've rebased off latest master. I'm testing this to see if it meets the solves for enabling [multi-auth](https://getkong.org/docs/0.10.x/auth/#multiple-authentication) and it unfortunately doesn't seem to.  I'm using the following consumer to test:

    consumers:
      - username: anon
        custom_id: anon

It does work for setting up the request-termination plugin globally (using username:anon only, custom_id: anon failed):

    - name: request-termination
      username: anon
      attributes:
        enabled: true
        config:
          status_code: 403
          message: Authentication failed.

However, it doesn't address the anonymous property in the auth plugins:

    apis:
      - name: api-test
        plugins:
          - name: jwt_ku
            attributes:
              enabled: true
              config:
                claims_to_verify: exp
                key_claim_name: iss
                anonymous: anon
                secret_is_base64: true
                uri_param_names:
                  - jwt
        attributes:
          uris:
            - /test
          strip_uri: true
          preserve_host: false
          upstream_url: 'http://my-service/test'

Any chance this could also be made to apply for the anonymous property on those auth plugins?

**Comment by CyExy** [comment]
@tophercullen I was trying to work out can we support custom_id mapping but because kong itself doesn't treat this as a unique ID there isn't really a good case for supporting it.

@thehighlander This PR adds support for anonymous config mapping, notice that the key is `anonymous_username`.

**Pull request merged**
