### PR TITLE
Add support for consumer IDs in plugins

### LINKED ISSUE #70: Consumer plugins are unsupported
I found this issue while Trying to configure the rate-limiting plugin various ways. See example config below

```
apis:
  - name: someapi 
    ensure: "present" 
    attributes: .....
    plugins:
      - name: rate-limiting 
        ensure: "present" 
        attributes: 
          consumer_id: ID1
          config:
            minute: 1
      - name: rate-limiting 
        ensure: "present" 
        attributes: 
          consumer_id: ID2
          config:
            minute: 2`

plugins:
  - name: rate-limiting
    ensure: "present"
    attributes:
      consumer_id: ID1
      config:
        minute: 10
```

The result after running is something as follows:

```    
{
      "consumer_id": "ID1",
      "id": "someUUID",
      "enabled": true,
      "name": "rate-limiting"
      ....
         minute: 10
.     ....
    },
    {
      "consumer_id": "ID2",
      "api_id": "myapiID",
      "id": "someUUID",
      "enabled": true,
      "name": "rate-limiting",
      ......
         minute: 2
      ......
    }
```

This is not the desired outcome. Instead of two plugins being created for ID1, one with only an consumer_id and another with both consumer and api IDs, there is a singular plugin with a consumer_id. Meaning the global plugin config took precedence. 

Further subsequent runs with the same config fails:

```
POST 409 http://kong:8001/plugins 
 { consumer_id: 'ID1',
  config: { minute: 10 },
  name: 'rate-limiting' }
Error: Conflict
{"name":"already exists with value 'rate-limiting'"}
```

Similarly, If a global plugin exists, without a customer_id, it will succeed the first time, by converting the global plugin to one bound to a consumer_id. Subsequent runs will fail for a similar reason

It shouldn't come as a surprise that creating a generic global plugin again, then running the config again results it in being converted, and having duplicate identical global plugins which are essentially invisible to kongfig

At least for the global plugin, the core reason seems to be the global plugin discovery explicitly filters out plugin results that have a consumer or api ID (see https://github.com/mybuilder/kongfig/blob/master/src/kongState.js#L45)

### PR DESCRIPTION
**Pull request by tophercullen**
Fixes #70

### CODE REVIEW

**Comment by CyExy** [comment]
Thanks for the PR! Sorry for the delay, I'll check it out when I get back to the office that should happen be in couple of days.

**Comment by sarraz1** [comment]
Hello, I'm going to test and review your fix.

**Comment by sarraz1** [comment]
A problems is that when I dump the configuration, consumer_id is lost.

Note that if consumer_id was present, the dumped file could not be used in the case the consumers have to be recreated (consumer_id would be regenerated and so the plugins configurations would be false). Nevertheless you must add consumer_id. Else the applied configuration from the dump would not be the initial one and it's better to have an consumer_id error to fix instead having a bad configuration.

**Comment by tophercullen** [comment]
As far as being lost, I reproduced that locally. adding consumer_id to the plugin dump fixes that nicely.

As far as the consumer_id existence, that touches on some key features that are missing, but required for multi-environment management. That is beyond the scope for this PR. However, I'm working through how to solve that exactly

**Comment by CyExy** [comment]
Thanks for the PR.

Using the consumer ID can be problematic because they are generated when the consumer is added to Kong.

Maybe adding consumer specific plugins alongside consumer or reference a consumer using the username?

**Comment by tophercullen** [comment]
The random nature of the consumer ID is different problem I'm working on (see #75). Given that specify any attributes is currently allowed, I see two options:

- Make the plugin aware and handle consumer_ids appropriately (this pr)
- disallowed the consumer_id attribute since they can't handle them.

**Comment by sarraz1** [comment]
I think that reference the consumer by username in plugins is the better solution. 

Else and supposing consumers were created first, we can generate kongfig files using kong rest api to find the consumer_id.

Tool like ansible with usage of template file can help to wrap kongfig and implement such a mechanism.

**Comment by tophercullen** [comment]
I think you are misunderstanding. This PR is still needed even if a username is provided or some other resource (like ansible) does the mapping. The plugin functions will still need to be able to compare plugins with consumer_ids or specifically disallow it in some way. Else the same problems, like #68 and #70, are going to keep popping up.

**Comment by sarraz1** [comment]
But I have never said the opposite, this discussion is based on a remark and I agree that your PR is not directly questionned and consumers id is fundamental in kong plugins. I did not study the problem in détails but I guess we would add methods such find_consumer_by_username_or_id. 

Nevertheless in your working PR request about username, be aware to not diverge from kong "evolving" rest api. In my sense, that's the kongfig file respect of kong api specifications which makes  kongfig reliable.

**Comment by sarraz1** [comment]
My tests have been passed successfuly.
A lot a combination of rate-limiting api plugins and global plugins (with and without consumer_id).
It should work on the other plugins too. 

#70 is solved, nice work !

**Pull request merged**
